#!/usr/bin/env python3
"""Regenerate config/demo_map.yaml to match landmark_sim_demo's seeded RNG.

The sim uses mt19937 with seed 7 and uniform draws:
  x,y ~ U(0.5, 9.5)   z ~ U(0.2, 3.0)
in the exact order: for each landmark: x, y, z.
"""

import numpy as np

rng = np.random.default_rng(7)
# NOTE: the sim uses std::mt19937 + uniform_real_distribution, NOT numpy.
# This script reproduces the C++ sequence exactly via the same algorithm.
# numpy's default_rng(7) does NOT match mt19937(7), so we implement the C++
# uniform_real_distribution draw: canonical double from 32-bit MT output.


class MT19937Cpp:
    """Exact std::mt19937 + std::uniform_real_distribution<double> semantics."""

    def __init__(self, seed: int):
        self.mt = [0] * 624
        self.mt[0] = seed & 0xFFFFFFFF
        for i in range(1, 624):
            self.mt[i] = (1812433253 * (self.mt[i - 1] ^ (self.mt[i - 1] >> 30)) + i) & 0xFFFFFFFF
        self.idx = 624

    def generate(self):
        for i in range(624):
            y = (self.mt[i] & 0x80000000) + (self.mt[(i + 1) % 624] & 0x7FFFFFFF)
            self.mt[i] = self.mt[(i + 397) % 624] ^ (y >> 1)
            if y % 2 != 0:
                self.mt[i] ^= 0x9908B0DF
        self.idx = 0

    def next_u32(self):
        if self.idx >= 624:
            self.generate()
        y = self.mt[self.idx]
        self.idx += 1
        y ^= y >> 11
        y ^= (y << 7) & 0x9D2C5680
        y ^= (y << 15) & 0xEFC60000
        y ^= y >> 18
        return y & 0xFFFFFFFF

    def uniform(self, a: float, b: float) -> float:
        # libstdc++ generate_canonical<double, 53>: two 32-bit draws
        lo = self.next_u32()
        hi = self.next_u32()
        r = (lo + hi * 4294967296.0) / 18446744073709551616.0
        return r * (b - a) + a


def main():
    mt = MT19937Cpp(7)
    lines = ["# Generated by scripts/gen_demo_map.py (matches landmark_sim_demo seed 7)"]
    for i in range(30):
        x = mt.uniform(0.5, 9.5)
        y = mt.uniform(0.5, 9.5)
        z = mt.uniform(0.2, 3.0)
        lines.append(f"{i}: [{x:.6f}, {y:.6f}, {z:.6f}]")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
